"""Add is_ai_processing to Ticket

Revision ID: e6737e47e256
Revises: 825fdc503106
Create Date: 2026-09-22 12:50:14.167487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6737e47e256'
down_revision: Union[str, None] = '825fdc503106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_ai_processing', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_tickets_is_ai_processing'), 'tickets', ['is_ai_processing'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_is_ai_processing'), table_name='tickets')
    op.drop_column('tickets', 'is_ai_processing')
    # ### end Alembic commands ###
